### ISSUE TITLE
Did you consider adding the package to PGXN

### ISSUE THREAD

**Issue by dnsl48** [pgMemento/pgMemento#17]
Hi @FxKu, thank you for creating such an awesome tool!

Did you consider adding it to the PGXN registry? I guess this might help more people to find it.
If you don't have time, I could perhaps write an initial META.json spec file and make a PR to this repo, but I guess you'd still have to upload the final package to PGXN as the author.

Let me know what you think.
Cheers

**Comment by FxKu** [comment]
Thanks @dnsl48 

Sounds like a very good idea. Also had some plans to create an extension, but was afraid it might then be harder to use for Win-users (because I don't want to provide binaries). But even with PGXN / extension, one could still you use the plain SQL.

Currently, I spend all the spare time I have on fixing stuff so I would really appreciate if you could provide an PR.
