### ISSUE TITLE
pg_dump loses history data

### ISSUE THREAD

**Issue by dnsl48** [pgMemento/pgMemento#23]
When restoring data from backup some history data appears to be lost.

More details are here: https://github.com/pgMemento/pgMemento/pull/19#issuecomment-466688481

**Comment by dnsl48** [comment]
This is a show-stopper to me. I may start investigating possible solutions straight away.

**Comment by dnsl48** [comment]
> added the enhancement label 23 hours ago

In my use case I treat the historic data as part of the main application data.
This is a similar use case to how e.g. MediaWiki (Wikipedia platform) treats article history. It keeps all the changes as separate revisions.

In such use case losing that information is intolerable and I consider this issue to be rather a bug than enhancement.

**Comment by FxKu** [comment]
We're not at 1.0, yet ;-)

I agree, that loosing the history is not tolerable and it has to be fixed. But, as this weakness has lived in pgMemento for a long time and nobody complained so far, I don't see a big problem of doing a release now (well, this month) and aiming for a v0.8 that solves it. I would feel more comfortable to break things after v0.7.

**Comment by dnsl48** [comment]
Sure, I'm merely saying the type of the issue feels like a bug rather than enhancement IHMO :)
I don't think that should block the release as there are no benefits in it.

**Comment by FxKu** [comment]
Changed my mind and started working on getting rid of OIDs. Breaking changes ahead...

**Comment by davenquinn** [comment]
Hi @FxKu , thanks for working on this. Are these changes you mentioned implemented and merged? I am planning to implement pg-memento in a new project soon, and I would like the audit trail to be independent of OIDs since my backup strategy is built atop `pg_dump`. I also would prefer not to change the schema drastically soon after integrating; I'd be happy to work off an unstable branch right now to do initial testing, if you could point me to which one to look at.

**Comment by davenquinn** [comment]
Actually, it appears that the `dev` branch has corresponding activity; would you caution against me trying to use `dev` until these changes are merged into `master`?

**Comment by FxKu** [comment]
You got it right, the `dev` branch contains the newest code base. Had to change quite a bit to leave OIDs behind, but the refactoring is already complete (incl. some breaking API changes). It just isn't merged yet because I haven't find the time yet, to write UPGRADE scripts and update the documentation (new job, new OS project etc.). I've also thought that it's a good time to address the other open issues, as they would also require more breaking changes.

Feel free to give it a shot. Now is a good time for feature requests :)

**Comment by dnsl48** [comment]
is it all going to land to 0.7 release?

**Comment by FxKu** [comment]
What's in the dev branch, yes. And then I (we) have to consider what else to include, e.g. I don't want to introduce new columns to log tables in every release :) (see #26 #27)
