### ISSUE TITLE
0.7 release date

### ISSUE THREAD

**Issue by nextstopsun** [pgMemento/pgMemento#38]
Any time estimates on when 0.7 would be released? 
It'd be great to have an extension instead of installation script. 
Extension is way more migration friendly.

**Comment by FxKu** [comment]
I will try to work on some of the open issues I have on my list for 0.7. They might require some more changes on the log tables. That's why I haven't drafted another release yet. Aiming for having another release this year.

**Comment by paulrizzo** [comment]
@FxKu it appears you are getting close on a release for 0.7 and was wondering if you have a rough target date in mind. I am currently using Postgres 10.10 and am looking to move to 12.2 but that requires some of the changes you have currently in master branch. If you need any help getting 0.7 across the line please let me know.

**Comment by FxKu** [comment]
Thanks @paulrizzo for the offer. Yes, I'm close doing a 0.7 release. Basically, the only open point left is PR #24 which I'd really like to include in the release. It should be ready by april or even sooner if it will be forbidden to go out because of the virus. Lets see. It would be really nice if you could test the current master and file bug reports, if you find them :smiley:

**Comment by paulrizzo** [comment]
@FxKu Thank you for the update. I will pull the latest master, test it out, and log any issues I find.

**Comment by FxKu** [comment]
Aaaand it's out: https://github.com/pgMemento/pgMemento/releases/tag/v0.7
Took a lot longer than I thought, but I really wanted to include as many breaking changes as possible before publishing the extension :smiley:
